-- HACER UNA BASE DE DATOS EN LA CUAL SE MANEJE EL DIRECTORIO DE ALUMNOS DE UN COLEGIO
-- EL COLEGIO SOLO TIENE UN AÑO Y UNA SECCION PERO SI MANEJA VARIOS CURSOS QUE SON
-- COMUNICACION, CTA, INGLES, FRENCH
-- EL ALUMNO TIENE UN NOMBRE, APELLIDO, CORREO
-- UN ALUMNO PUEDE LLEVAR VARIOS CURSOS Y UN CURSO PUEDE TENER VARIOS ALUMNOS

CREATE DATABASE colegio;
CREATE TABLE ALUMNOS(...);
CREATE TABLE CURSOS(...);
CREATE TABLE ALUMNOS_CURSOS(...);